implementation de Swagger
MetaClub/api-metaclub pull request #3
Opened 2016-11-19 23:50 UTC by duckish

2016-11-22 05:21 UTC, RignonNoel requested changes
Il faudrais mettre les numeros de version dans le requirements.txt

2016-11-26 23:36 UTC, RignonNoel approved these changes

2016-11-27 00:18 UTC, Gasuleg approved these changes

2016-11-27 00:20 UTC, samdidos approved these changes

2016-11-27 00:21 UTC, merged

2016-11-27 00:21 UTC, RignonNoel commented
@duckish Merci beaucp =)